# src/data_loader.py
import json
import csv

def load_from_dict_format():
    """
    Temporary sample data (for early project stage)
    Returns { u: {v: weight, ...}, ... }
    """
    return {
        "A": {"B": 4, "C": 2},
        "B": {"C": 5, "D": 10},
        "C": {"E": 3},
        "E": {"D": 4},
        "D": {}
    }

def load_from_json(filepath):
    """
    Load standard JSON format { "A": {"B":4, "C":2}, ... }
    """
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data

def load_from_csv(filepath):
    """
    Load CSV format: each line u,v,weight
    """
    data = {}
    with open(filepath, newline='', encoding='utf-8') as csvfile:
        reader = csv.reader(csvfile)
        for row in reader:
            if not row or len(row) < 3:
                continue
            u, v, w = row[0].strip(), row[1].strip(), float(row[2])
            if u not in data:
                data[u] = {}
            data[u][v] = w
            # Ensure v exists (may have no outgoing edges)
            if v not in data:
                data[v] = {}
    return data

def load_metro_adjacency(filepath):
    """
    Load adjacency.json generated by metro scripts (nyc/london/chicago)
    Format: { "node_id": {"neighbor_id": weight, ...} }
    Returns dict directly usable by Graph.load_from_dict
    """
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data  # Already in correct {u: {v: w}} format